export const darkColorHexes = [
  '#2E3D7C',
  '#FFA73C',
  '#E15D3A',
  '#BA292E',
  '#282528',
  '#217CA3',
  '#E29930',
  '#32384D',
  '#211F30',
  '#F15E37',
  '#2C3F99',
  '#70CBD2',
  '#02120E',
]

export const darkColorHexesRepeated = [
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
  ...darkColorHexes,
]
